/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeRouteImport } from './routes/tree'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as OrchestratorRouteImport } from './routes/orchestrator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActorIdRouteImport } from './routes/actor.$id'

const TreeRoute = TreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestratorRoute = OrchestratorRouteImport.update({
  id: '/orchestrator',
  path: '/orchestrator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorIdRoute = ActorIdRouteImport.update({
  id: '/actor/$id',
  path: '/actor/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/orchestrator': typeof OrchestratorRoute
  '/review': typeof ReviewRoute
  '/tree': typeof TreeRoute
  '/actor/$id': typeof ActorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/orchestrator': typeof OrchestratorRoute
  '/review': typeof ReviewRoute
  '/tree': typeof TreeRoute
  '/actor/$id': typeof ActorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/orchestrator': typeof OrchestratorRoute
  '/review': typeof ReviewRoute
  '/tree': typeof TreeRoute
  '/actor/$id': typeof ActorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/orchestrator'
    | '/review'
    | '/tree'
    | '/actor/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/orchestrator' | '/review' | '/tree' | '/actor/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/orchestrator'
    | '/review'
    | '/tree'
    | '/actor/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  OrchestratorRoute: typeof OrchestratorRoute
  ReviewRoute: typeof ReviewRoute
  TreeRoute: typeof TreeRoute
  ActorIdRoute: typeof ActorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestrator': {
      id: '/orchestrator'
      path: '/orchestrator'
      fullPath: '/orchestrator'
      preLoaderRoute: typeof OrchestratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actor/$id': {
      id: '/actor/$id'
      path: '/actor/$id'
      fullPath: '/actor/$id'
      preLoaderRoute: typeof ActorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  OrchestratorRoute: OrchestratorRoute,
  ReviewRoute: ReviewRoute,
  TreeRoute: TreeRoute,
  ActorIdRoute: ActorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
