package schemadoc

import (
	"fmt"
	"reflect"
	"sort"
	"strings"

	"github.com/poteto/noodle/internal/queuex"
	"github.com/poteto/noodle/mise"
)

// FieldDoc is the canonical schema metadata for one leaf field.
type FieldDoc struct {
	Type        string
	Description string
}

// TargetInfo describes one schema target exposed by the CLI.
type TargetInfo struct {
	Name        string
	FileName    string
	Description string
}

type targetSpec struct {
	Info        TargetInfo
	RootType    reflect.Type
	FieldDocs   map[string]FieldDoc
	Constraints []string
}

var schemaTargets = []targetSpec{
	{
		Info: TargetInfo{
			Name:        "mise",
			FileName:    "mise.json",
			Description: "Input to prioritize; generated by `noodle mise`.",
		},
		RootType: reflect.TypeOf(mise.Brief{}),
		FieldDocs: map[string]FieldDoc{
			"generated_at":                  {Type: "RFC3339 timestamp", Description: "time the brief was generated"},
			"backlog[].id":                  {Description: "unique backlog item ID"},
			"backlog[].title":               {Description: "backlog item title"},
			"backlog[].description":         {Description: "backlog item details"},
			"backlog[].section":             {Description: "backlog section grouping"},
			"backlog[].status":              {Type: "string (open|in_progress|done)", Description: "backlog workflow status"},
			"backlog[].tags[]":              {Description: "backlog tag"},
			"backlog[].plan":                {Description: "linked plan directory slug"},
			"backlog[].plan_phase":          {Description: "active plan phase filename"},
			"backlog[].estimate":            {Type: "string (small|medium|large)", Description: "size estimate"},
			"plans[].id":                    {Type: "number", Description: "plan ID"},
			"plans[].title":                 {Description: "plan title"},
			"plans[].status":                {Type: "string (draft|active|done)", Description: "plan status"},
			"plans[].provider":              {Description: "optional plan-level provider hint"},
			"plans[].model":                 {Description: "optional plan-level model hint"},
			"plans[].directory":             {Description: "plan directory slug"},
			"plans[].phases[].name":         {Description: "phase display name"},
			"plans[].phases[].filename":     {Description: "phase file basename"},
			"plans[].phases[].status":       {Type: "string (pending|active|done)", Description: "phase status"},
			"active_cooks[].id":             {Description: "cook session ID"},
			"active_cooks[].target":         {Description: "backlog item currently assigned"},
			"active_cooks[].provider":       {Description: "agent provider"},
			"active_cooks[].model":          {Description: "model identifier"},
			"active_cooks[].status":         {Description: "session status"},
			"active_cooks[].cost":           {Type: "number", Description: "cost in USD"},
			"active_cooks[].duration_s":     {Type: "number", Description: "elapsed seconds"},
			"tickets[].target":              {Description: "claimed target ID"},
			"tickets[].target_type":         {Type: "string (backlog_item|file|plan_phase)", Description: "ticket target category"},
			"tickets[].cook_id":             {Description: "session holding the claim"},
			"tickets[].files[]":             {Description: "claimed file path"},
			"tickets[].claimed_at":          {Type: "RFC3339 timestamp", Description: "claim start timestamp"},
			"tickets[].last_progress":       {Type: "RFC3339 timestamp", Description: "most recent progress timestamp"},
			"tickets[].status":              {Type: "string (active|blocked|stale)", Description: "materialized ticket status"},
			"tickets[].blocked_by":          {Description: "blocking dependency ID"},
			"tickets[].reason":              {Description: "block or stale reason"},
			"resources.max_cooks":           {Type: "number", Description: "configured concurrency limit"},
			"resources.active":              {Type: "number", Description: "currently active cooks"},
			"resources.available":           {Type: "number", Description: "remaining available cook slots"},
			"recent_history[].target":       {Description: "target worked during the session"},
			"recent_history[].cook_id":      {Description: "session ID"},
			"recent_history[].outcome":      {Description: "session outcome"},
			"recent_history[].cost":         {Type: "number", Description: "session cost in USD"},
			"recent_history[].duration_s":   {Type: "number", Description: "session duration in seconds"},
			"routing.defaults.provider":     {Description: "default provider"},
			"routing.defaults.model":        {Description: "default model"},
			"routing.tags{}.provider":       {Description: "tag-specific provider override"},
			"routing.tags{}.model":          {Description: "tag-specific model override"},
			"task_types[].key":              {Description: "task type key"},
			"task_types[].blocking":         {Type: "boolean", Description: "whether this task type blocks other work"},
			"task_types[].schedule":         {Description: "when this task type is normally scheduled"},
			"quality_verdicts[].session_id": {Description: "quality session ID"},
			"quality_verdicts[].target_id":  {Description: "target reviewed by quality"},
			"quality_verdicts[].accept":     {Type: "boolean", Description: "quality pass/fail verdict"},
			"quality_verdicts[].feedback":   {Description: "review feedback"},
			"quality_verdicts[].timestamp":  {Type: "RFC3339 timestamp", Description: "verdict timestamp"},
			"warnings[]":                    {Description: "operational warning message"},
		},
	},
	{
		Info: TargetInfo{
			Name:        "queue",
			FileName:    "queue.json",
			Description: "Output of prioritize; consumed by the dispatcher.",
		},
		RootType: reflect.TypeOf(queuex.Queue{}),
		FieldDocs: map[string]FieldDoc{
			"generated_at":      {Type: "RFC3339 timestamp", Description: "time the queue was generated"},
			"items[].id":        {Description: "queue item ID"},
			"items[].task_key":  {Description: "must match a task_types[].key from mise"},
			"items[].title":     {Description: "brief task description"},
			"items[].provider":  {Description: "provider used for this task"},
			"items[].model":     {Description: "model used for this task"},
			"items[].runtime":   {Description: "runtime used for this task (tmux, sprites, etc.)"},
			"items[].skill":     {Description: "skill name to load"},
			"items[].plan[]":    {Description: "linked plan path(s), e.g. plans/15-bootstrap-onboarding/overview"},
			"items[].review":    {Type: "boolean", Description: "true when this item requires blocking review"},
			"items[].rationale": {Description: "placement reason citing a rule or principle"},
			"active[]":          {Description: "queue item IDs currently being cooked"},
			"action_needed[]":   {Description: "backlog item ID skipped pending user action"},
			"autonomy":          {Description: "current runtime autonomy mode (full, review, approve)"},
		},
		Constraints: []string{
			"Items must respect workflow order: execute -> quality (blocking) -> reflect.",
			"When any item has `\"review\": true`, it must be the only item type in the queue.",
			"Task keys must match a `task_types[].key` from mise.",
			"Each `rationale` should cite a specific scheduling rule or principle.",
		},
	},
}

func listTargets() []TargetInfo {
	out := make([]TargetInfo, len(schemaTargets))
	for i, target := range schemaTargets {
		out[i] = target.Info
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func targetByName(name string) (targetSpec, error) {
	name = strings.TrimSpace(strings.ToLower(name))
	for _, target := range schemaTargets {
		if target.Info.Name == name {
			return target, nil
		}
	}
	return targetSpec{}, fmt.Errorf("schema target not found: %s", name)
}
