package schemadoc

import (
	"fmt"
	"reflect"
	"sort"
	"strings"

	"github.com/poteto/noodle/internal/orderx"
	"github.com/poteto/noodle/internal/statusfile"
	"github.com/poteto/noodle/mise"
)

// FieldDoc is the canonical schema metadata for one leaf field.
type FieldDoc struct {
	Type        string
	Description string
}

// TargetInfo describes one schema target exposed by the CLI.
type TargetInfo struct {
	Name        string
	FileName    string
	Description string
}

type targetSpec struct {
	Info        TargetInfo
	RootType    reflect.Type
	FieldDocs   map[string]FieldDoc
	Constraints []string
}

var schemaTargets = []targetSpec{
	{
		Info: TargetInfo{
			Name:        "mise",
			FileName:    "mise.json",
			Description: "Input to schedule; generated by `noodle mise`.",
		},
		RootType: reflect.TypeOf(mise.Brief{}),
		FieldDocs: map[string]FieldDoc{
			"generated_at":                  {Type: "RFC3339 timestamp", Description: "time the brief was generated"},
			"backlog[].id":                  {Description: "unique backlog item ID"},
			"backlog[].title":               {Description: "backlog item title"},
			"backlog[].description":         {Description: "backlog item details"},
			"backlog[].section":             {Description: "backlog section grouping"},
			"backlog[].status":              {Type: "string (open|in_progress|done)", Description: "backlog workflow status"},
			"backlog[].tags[]":              {Description: "backlog tag"},
			"backlog[].estimate":            {Type: "string (small|medium|large)", Description: "size estimate"},
			"backlog[].plan":                {Description: "optional path to plan overview file (e.g. brain/plans/29-context-passthrough/overview.md)"},
			"active_summary.total":          {Type: "number", Description: "total active sessions"},
			"active_summary.by_task_key{}":  {Type: "number", Description: "active sessions grouped by task key"},
			"active_summary.by_status{}":    {Type: "number", Description: "active sessions grouped by status"},
			"active_summary.by_runtime{}":   {Type: "number", Description: "active sessions grouped by runtime"},
			"tickets[].target":              {Description: "claimed target ID"},
			"tickets[].target_type":         {Type: "string (backlog_item|file|plan_phase)", Description: "ticket target category"},
			"tickets[].cook_id":             {Description: "session holding the claim"},
			"tickets[].files[]":             {Description: "claimed file path"},
			"tickets[].claimed_at":          {Type: "RFC3339 timestamp", Description: "claim start timestamp"},
			"tickets[].last_progress":       {Type: "RFC3339 timestamp", Description: "most recent progress timestamp"},
			"tickets[].status":              {Type: "string (active|blocked|stale)", Description: "materialized ticket status"},
			"tickets[].blocked_by":          {Description: "blocking dependency ID"},
			"tickets[].reason":              {Description: "block or stale reason"},
			"resources.max_cooks":           {Type: "number", Description: "configured concurrency limit"},
			"resources.active":              {Type: "number", Description: "currently active cooks"},
			"resources.available":           {Type: "number", Description: "remaining available cook slots"},
			"recent_history[].session_id":   {Description: "session ID"},
			"recent_history[].order_id":     {Description: "order ID associated with the session"},
			"recent_history[].task_key":     {Description: "task key completed by the session"},
			"recent_history[].status":       {Description: "completion status for the session"},
			"recent_history[].duration_s":   {Type: "number", Description: "session duration in seconds"},
			"recent_history[].completed_at": {Type: "RFC3339 timestamp", Description: "completion timestamp"},
			"recent_events[].type":          {Description: "lifecycle event type"},
			"recent_events[].seq":           {Type: "number", Description: "event sequence number"},
			"recent_events[].at":            {Type: "RFC3339 timestamp", Description: "event timestamp"},
			"recent_events[].summary":       {Description: "event summary description"},
			"routing.defaults.provider":     {Description: "default provider"},
			"routing.defaults.model":        {Description: "default model"},
			"routing.available_runtimes[]":  {Description: "runtime kinds available for scheduling"},
			"routing.tags{}.provider":       {Description: "tag-specific provider override"},
			"routing.tags{}.model":          {Description: "tag-specific model override"},
			"task_types[].key":              {Description: "task type key"},
			"task_types[].schedule":         {Description: "when this task type is normally scheduled"},
			"warnings[]":                    {Description: "operational warning message"},
		},
	},
	{
		Info: TargetInfo{
			Name:        "orders",
			FileName:    "orders.json",
			Description: "Output of schedule (written to orders-next.json); promoted to orders.json by the loop.",
		},
		RootType: reflect.TypeOf(orderx.OrdersFile{}),
		FieldDocs: map[string]FieldDoc{
			"generated_at":                   {Type: "RFC3339 timestamp", Description: "time the orders were generated"},
			"orders[].id":                    {Description: "order ID (plan ID as string, or unique slug)"},
			"orders[].title":                 {Description: "brief order description"},
			"orders[].plan[]":                {Description: "linked plan path(s), e.g. plans/15-bootstrap-onboarding/overview"},
			"orders[].rationale":             {Description: "placement reason citing a rule or principle"},
			"orders[].stages[].task_key":     {Description: "must match a task_types[].key from mise"},
			"orders[].stages[].prompt":       {Description: "full prompt text for the dispatched session"},
			"orders[].stages[].skill":        {Description: "skill name to load"},
			"orders[].stages[].provider":     {Description: "provider used for this stage"},
			"orders[].stages[].model":        {Description: "model used for this stage"},
			"orders[].stages[].runtime":      {Description: "runtime used for this stage (process, sprites, etc.)"},
			"orders[].stages[].group":        {Type: "number (optional)", Description: "parallel group ID; stages in the same group run concurrently, groups execute sequentially (default: 0)"},
			"orders[].stages[].status":       {Type: "string (pending|active|completed|failed|cancelled)", Description: "stage lifecycle status"},
			"orders[].stages[].extra{}[]":    {Description: "opaque extension data preserved across round-trips"},
			"orders[].stages[].extra_prompt": {Description: "supplemental instructions for the cook on how to approach the task (max ~1000 chars)"},
			"orders[].status":                {Type: "string (active|completed|failed)", Description: "order lifecycle status"},
			"action_needed[]":                {Description: "backlog item ID skipped pending user action"},
		},
		Constraints: []string{
			"Each order is a pipeline of stage groups executed sequentially. Stages within the same group run concurrently.",
			"Group related work (execute, quality, reflect) into stages within one order.",
			"Stage task keys must match a `task_types[].key` from mise.",
			"Each `rationale` should cite a specific scheduling rule or principle.",
		},
	},
	{
		Info: TargetInfo{
			Name:        "status",
			FileName:    "status.json",
			Description: "Runtime state written by the loop; read by TUI and CLI.",
		},
		RootType: reflect.TypeOf(statusfile.Status{}),
		FieldDocs: map[string]FieldDoc{
			"active[]":   {Description: "order IDs currently being cooked"},
			"loop_state": {Description: "current loop state (running, paused, draining, idle)"},
			"mode":       {Type: "string (auto|supervised|manual)", Description: "current run mode governing schedule, dispatch, retry, and merge gates"},
			"max_cooks":  {Type: "number", Description: "current max concurrency (may differ from config if overridden at runtime)"},
		},
	},
}

func listTargets() []TargetInfo {
	out := make([]TargetInfo, len(schemaTargets))
	for i, target := range schemaTargets {
		out[i] = target.Info
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func targetByName(name string) (targetSpec, error) {
	name = strings.TrimSpace(strings.ToLower(name))
	for _, target := range schemaTargets {
		if target.Info.Name == name {
			return target, nil
		}
	}
	return targetSpec{}, fmt.Errorf("schema target not found: %s", name)
}
