package schemadoc

import (
	"fmt"
	"reflect"
	"sort"
	"strings"

	"github.com/poteto/noodle/internal/queuex"
	"github.com/poteto/noodle/internal/statusfile"
	"github.com/poteto/noodle/mise"
)

// FieldDoc is the canonical schema metadata for one leaf field.
type FieldDoc struct {
	Type        string
	Description string
}

// TargetInfo describes one schema target exposed by the CLI.
type TargetInfo struct {
	Name        string
	FileName    string
	Description string
}

type targetSpec struct {
	Info        TargetInfo
	RootType    reflect.Type
	FieldDocs   map[string]FieldDoc
	Constraints []string
}

var schemaTargets = []targetSpec{
	{
		Info: TargetInfo{
			Name:        "mise",
			FileName:    "mise.json",
			Description: "Input to schedule; generated by `noodle mise`.",
		},
		RootType: reflect.TypeOf(mise.Brief{}),
		FieldDocs: map[string]FieldDoc{
			"generated_at":                  {Type: "RFC3339 timestamp", Description: "time the brief was generated"},
			"backlog[].id":                  {Description: "unique backlog item ID"},
			"backlog[].title":               {Description: "backlog item title"},
			"backlog[].description":         {Description: "backlog item details"},
			"backlog[].section":             {Description: "backlog section grouping"},
			"backlog[].status":              {Type: "string (open|in_progress|done)", Description: "backlog workflow status"},
			"backlog[].tags[]":              {Description: "backlog tag"},
			"backlog[].estimate":            {Type: "string (small|medium|large)", Description: "size estimate"},
			"plans[].id":                    {Type: "number", Description: "plan ID"},
			"plans[].title":                 {Description: "plan title"},
			"plans[].status":                {Type: "string (draft|active|done)", Description: "plan status"},
			"plans[].provider":              {Description: "optional plan-level provider hint"},
			"plans[].model":                 {Description: "optional plan-level model hint"},
			"plans[].backlog":               {Description: "backlog item ID linked in plan frontmatter"},
			"plans[].directory":             {Description: "plan directory slug"},
			"plans[].phases[].name":         {Description: "phase display name"},
			"plans[].phases[].filename":     {Description: "phase file basename"},
			"plans[].phases[].status":       {Type: "string (pending|active|done)", Description: "phase status"},
			"active_cooks[].id":             {Description: "cook session ID"},
			"active_cooks[].target":         {Description: "backlog item currently assigned"},
			"active_cooks[].provider":       {Description: "agent provider"},
			"active_cooks[].model":          {Description: "model identifier"},
			"active_cooks[].status":         {Description: "session status"},
			"active_cooks[].cost":           {Type: "number", Description: "cost in USD"},
			"active_cooks[].duration_s":     {Type: "number", Description: "elapsed seconds"},
			"tickets[].target":              {Description: "claimed target ID"},
			"tickets[].target_type":         {Type: "string (backlog_item|file|plan_phase)", Description: "ticket target category"},
			"tickets[].cook_id":             {Description: "session holding the claim"},
			"tickets[].files[]":             {Description: "claimed file path"},
			"tickets[].claimed_at":          {Type: "RFC3339 timestamp", Description: "claim start timestamp"},
			"tickets[].last_progress":       {Type: "RFC3339 timestamp", Description: "most recent progress timestamp"},
			"tickets[].status":              {Type: "string (active|blocked|stale)", Description: "materialized ticket status"},
			"tickets[].blocked_by":          {Description: "blocking dependency ID"},
			"tickets[].reason":              {Description: "block or stale reason"},
			"resources.max_cooks":           {Type: "number", Description: "configured concurrency limit"},
			"resources.active":              {Type: "number", Description: "currently active cooks"},
			"resources.available":           {Type: "number", Description: "remaining available cook slots"},
			"recent_history[].target":       {Description: "target worked during the session"},
			"recent_history[].cook_id":      {Description: "session ID"},
			"recent_history[].outcome":      {Description: "session outcome"},
			"recent_history[].cost":         {Type: "number", Description: "session cost in USD"},
			"recent_history[].duration_s":   {Type: "number", Description: "session duration in seconds"},
			"routing.defaults.provider":     {Description: "default provider"},
			"routing.defaults.model":        {Description: "default model"},
			"routing.available_runtimes[]":  {Description: "runtime kinds available for scheduling"},
			"routing.tags{}.provider":       {Description: "tag-specific provider override"},
			"routing.tags{}.model":          {Description: "tag-specific model override"},
			"task_types[].key":              {Description: "task type key"},
			"task_types[].can_merge":        {Type: "boolean", Description: "whether successful runs can auto-merge"},
			"task_types[].schedule":         {Description: "when this task type is normally scheduled"},
			"warnings[]":                    {Description: "operational warning message"},
		},
	},
	{
		Info: TargetInfo{
			Name:        "orders",
			FileName:    "orders.json",
			Description: "Output of schedule (written to orders-next.json); promoted to orders.json by the loop.",
		},
		RootType: reflect.TypeOf(queuex.OrdersFile{}),
		FieldDocs: map[string]FieldDoc{
			"generated_at":                  {Type: "RFC3339 timestamp", Description: "time the orders were generated"},
			"orders[].id":                   {Description: "order ID (plan ID as string, or unique slug)"},
			"orders[].title":                {Description: "brief order description"},
			"orders[].plan[]":               {Description: "linked plan path(s), e.g. plans/15-bootstrap-onboarding/overview"},
			"orders[].rationale":            {Description: "placement reason citing a rule or principle"},
			"orders[].stages[].task_key":    {Description: "must match a task_types[].key from mise"},
			"orders[].stages[].prompt":      {Description: "full prompt text for the dispatched session"},
			"orders[].stages[].skill":       {Description: "skill name to load"},
			"orders[].stages[].provider":    {Description: "provider used for this stage"},
			"orders[].stages[].model":       {Description: "model used for this stage"},
			"orders[].stages[].runtime":     {Description: "runtime used for this stage (tmux, sprites, etc.)"},
			"orders[].stages[].status":      {Type: "string (pending|active|completed|failed|cancelled)", Description: "stage lifecycle status"},
			"orders[].stages[].extra{}[]":   {Description: "opaque extension data preserved across round-trips"},
			"orders[].status":               {Type: "string (active|completed|failed|failing)", Description: "order lifecycle status"},
			"orders[].on_failure[].task_key":  {Description: "recovery stage task type key"},
			"orders[].on_failure[].prompt":    {Description: "recovery stage prompt"},
			"orders[].on_failure[].skill":     {Description: "recovery stage skill name"},
			"orders[].on_failure[].provider":  {Description: "recovery stage provider"},
			"orders[].on_failure[].model":     {Description: "recovery stage model"},
			"orders[].on_failure[].runtime":   {Description: "recovery stage runtime"},
			"orders[].on_failure[].status":    {Type: "string (pending|active|completed|failed|cancelled)", Description: "recovery stage status"},
			"orders[].on_failure[].extra{}[]": {Description: "opaque extension data preserved across round-trips"},
			"action_needed[]":               {Description: "backlog item ID skipped pending user action"},
		},
		Constraints: []string{
			"Each order is a pipeline of stages executed sequentially.",
			"Group related work (execute, quality, reflect) into stages within one order.",
			"Stage task keys must match a `task_types[].key` from mise.",
			"Each `rationale` should cite a specific scheduling rule or principle.",
			"Use `on_failure` stages to define a recovery pipeline when the main pipeline fails.",
		},
	},
	{
		Info: TargetInfo{
			Name:        "status",
			FileName:    "status.json",
			Description: "Runtime state written by the loop; read by TUI and CLI.",
		},
		RootType: reflect.TypeOf(statusfile.Status{}),
		FieldDocs: map[string]FieldDoc{
			"active[]":   {Description: "queue item IDs currently being cooked"},
			"loop_state": {Description: "current loop state (running, paused, draining, idle)"},
			"autonomy":   {Description: "current runtime autonomy mode (auto, approve)"},
			"max_cooks":  {Type: "number", Description: "current max concurrency (may differ from config if overridden at runtime)"},
		},
	},
}

func listTargets() []TargetInfo {
	out := make([]TargetInfo, len(schemaTargets))
	for i, target := range schemaTargets {
		out[i] = target.Info
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func targetByName(name string) (targetSpec, error) {
	name = strings.TrimSpace(strings.ToLower(name))
	for _, target := range schemaTargets {
		if target.Info.Name == name {
			return target, nil
		}
	}
	return targetSpec{}, fmt.Errorf("schema target not found: %s", name)
}
