// Code generated by tygo. DO NOT EDIT.
import type { PendingReviewItem } from "./generated-loop-types";
export type { PendingReviewItem } from "./generated-loop-types";

//////////
// source: snapshot_builder.go

//////////
// source: types.go

/**
 * TraceFilter categorizes event lines for filtering.
 */
export type TraceFilter = string;
export const TraceFilterAll: TraceFilter = "all";
export const TraceFilterTools: TraceFilter = "tools";
export const TraceFilterThink: TraceFilter = "think";
export const TraceFilterTicket: TraceFilter = "ticket";
/**
 * LoopState constants.
 */
export const LoopStateRunning = "running";
/**
 * LoopState constants.
 */
export const LoopStatePaused = "paused";
/**
 * LoopState constants.
 */
export const LoopStateDraining = "draining";
/**
 * LoopState constants.
 */
export const LoopStateIdle = "idle";
/**
 * Health constants.
 */
export const HealthGreen = "green";
/**
 * Health constants.
 */
export const HealthYellow = "yellow";
/**
 * Health constants.
 */
export const HealthRed = "red";
/**
 * Snapshot is a point-in-time view of all loop state.
 */
export interface Snapshot {
  updated_at: string;
  loop_state: string;
  sessions: Session[];
  active: Session[];
  recent: Session[];
  orders: Order[];
  active_order_ids: string[];
  action_needed: string[];
  events_by_session: Record<string, EventLine[]>;
  feed_events: FeedEvent[];
  total_cost_usd: number /* float64 */;
  pending_reviews: PendingReviewItem[];
  pending_review_count: number /* int */;
  mode: string;
  max_cooks: number /* int */;
  warnings: string[];
}
/**
 * Session represents a single agent session.
 */
export interface Session {
  id: string;
  display_name: string;
  status: string;
  runtime: string;
  provider: string;
  model: string;
  total_cost_usd: number /* float64 */;
  duration_seconds: number /* int64 */;
  last_activity: string;
  current_action: string;
  health: string;
  context_window_usage_pct: number /* float64 */;
  retry_count: number /* int */;
  idle_seconds: number /* int64 */;
  stuck_threshold_seconds: number /* int64 */;
  loop_state: string;
  remote_host?: string;
  dispatch_warning?: string;
  worktree_name?: string;
  task_key?: string;
  title?: string;
}
/**
 * Order is a pipeline of stages in the snapshot.
 */
export interface Order {
  id: string;
  title?: string;
  plan?: string[];
  rationale?: string;
  stages: Stage[];
  status: string;
}
/**
 * Stage is a unit of work within an order in the snapshot.
 */
export interface Stage {
  task_key?: string;
  prompt?: string;
  skill?: string;
  provider: string;
  model: string;
  runtime?: string;
  group?: number /* int */;
  status: string;
  extra?: Record<string, unknown>;
  session_id?: string;
}
/**
 * EventLine is a single parsed event in a session trace.
 */
export interface EventLine {
  at: string;
  label: string;
  body: string;
  category: TraceFilter;
}
/**
 * FeedEvent is one event in the feed timeline.
 */
export interface FeedEvent {
  session_id: string;
  agent_name: string;
  task_type: string;
  at: string;
  label: string;
  body: string;
  category: string;
}
