// Code generated by tygo. DO NOT EDIT.

//////////
// source: pending_review.go

export interface PendingReviewItem {
  order_id: string;
  stage_index: number /* int */;
  task_key?: string;
  title?: string;
  prompt?: string;
  provider?: string;
  model?: string;
  runtime?: string;
  skill?: string;
  plan?: string[];
  rationale?: string;
  worktree_name: string;
  worktree_path: string;
  session_id?: string;
  reason?: string;
}
